import os

from dotenv import load_dotenv

load_dotenv()


TOKEN = os.getenv("TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
APPWRITE_ENDPOINT = os.getenv("APPWRITE_ENDPOINT")
APPWRITE_API_KEY = os.getenv("APPWRITE_API_KEY")
APPWRITE_PROJECT_ID = os.getenv("APPWRITE_PROJECT_ID")
APPWRITE_DB_ID = os.getenv("APPWRITE_DB_ID")
APPWRITE_COLLECTION_ID_MEETINGS = os.getenv("APPWRITE_COLLECTION_ID_MEETINGS")
APPWRITE_COLLECTION_ID_PEOPLE = os.getenv("APPWRITE_COLLECTION_ID_PEOPLE")
APPWRITE_BUCKET_ID_MEETINGS = os.getenv("APPWRITE_BUCKET_ID_MEETINGS")
ASSEMBLYAI_API_KEY = os.getenv("ASSEMBLYAI_API_KEY")
LLM_MODEL = "gemini-2.5-flash-lite-preview-06-17"

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
